### ISSUE TITLE
Consistent automatically selected color

### ISSUE THREAD

**Issue by mevdschee** [eddiejibson/avatars#10]
Thank you for your great script! Your code has:

    $random_color_key = array_rand($colors, 1);

The following code can ensure that the generated avatar has a consistent color (when the color is automatically selected):

    $random_color_key = hexdec(substr(md5($name), -8)) % count($colors);

Maybe that is a good idea to improve your script? Kind regards, Maurits

**Comment by eddiejibson** [comment]
Fixed in #14. Thanks again for all your suggestions, @mevdschee ! Take care

**Comment by mevdschee** [comment]
Thank you for your changes and for the excellent project! Kind regards, Maurits
