### ISSUE TITLE
Different letter selection

### ISSUE THREAD

**Issue by mevdschee** [eddiejibson/avatars#11]
Thank you for your great code! Your code takes the first letters of the first two words or the first two letters. Other scripts (such as Outlook) take the first letter of the first and last word. You have:

    $letters = grapheme_substr($name, 0, $length);
    if ($length > 1 && grapheme_strlen($name) > 2 && grapheme_strpos($name, " ") < grapheme_strlen($name)) {
        $letters = grapheme_substr($name, 0, 1) . grapheme_substr($name, grapheme_strpos($name, " ") + 1, 1);
    } else {
        $letters = grapheme_substr($name, 0, $length);
    }

You could consider doing:

    $letters = '';
    $words = preg_split('/[\s-]+/', $name);
    if ($length == 1) {
        $words = [$words[0]];
    } else {
        array_splice($words, $length - 1, count($words) - $length);
    }
    foreach ($words as $word) {
        if (ctype_digit($word) && strlen($word) == 1) {
            $letters .= $word;
        } else {
            $first = grapheme_substr($word, 0, 1);
            $letters .= ctype_digit($first) ? '' : $first;
        }
    }

Some test cases (current):

    Maurits van der Schee => Mv
    Maurits Eduard van der Schee => ME
    Maurits 2 => M2
    Maurits 1234 => M1
    maurits test => mt
    Maurits-Eduard => Ma
    Maurits Eduard van der Schee => MEv (length = 3)
    Maurits van der Schee => Mvd (length = 3)

Same test cases (proposed):

    Maurits van der Schee => MS
    Maurits 2 => M2
    Maurits 1234 => M
    maurits test => mt
    Maurits-Eduard => ME
    Maurits Eduard van der Schee => MES (length = 3)
    Maurits van der Schee => MvS (length = 3)

I'm not sure it is an improvement, but I felt like sharing. Keep up the good work!

See also: https://tqdev.com/2022-generate-avatars-initials-php

**Comment by eddiejibson** [comment]
@mevdschee Once again another great point! Didn't consider long names which was inconsiderdate of me. I've taken this and implemented it. I may try and improve the performance later. Next time, suggest the code in the PR so you get some credit being a contributor!

Fixed in #15

**Comment by mevdschee** [comment]
Thank you for your changes and for the excellent project!

>Next time, suggest the code in the PR so you get some credit being a contributor!

Sure, I will do that next time. I don't really care about the credit, so no harm is done. Thank you for your hard work and for sharing.
