### ISSUE TITLE
Make colors have the same saturation

### ISSUE THREAD

**Issue by mevdschee** [eddiejibson/avatars#12]
Thank you for your great code! The colors you have selected do not feel like a "set" to me. Some are very light, while others are really dark (I think it has something to do with saturation and lightness or distance to white). In your code you have:

`$colors = ["#E284B3", "#FFED8B",  "#681313", "#F3C1C6",  "#735372",  "#009975", "#FFBD39", "#B1E8ED", "#52437B", "#F76262", "#216583", "#293462", "#DD9D52", "#936B93", "#6DD38D", "#888888", "#6F8190", "#BCA0F0", "#AAF4DD", "#96C2ED", "#3593CE", "#5EE2CD", "#96366E", "#E38080"];`
    
And my proposal is to use:

`$colors = ['#e53935', '#d81b60', '#8e24aa', '#5e35b1', '#3949ab', '#1e88e5', '#039be5', '#00acc1', '#00897b', '#43a047', '#7cb342', '#c0ca33', '#fdd835', '#ffb300', '#fb8c00', '#f4511e', '#6d4c41', '#757575', '#546e7a'];`

These colors are used to color the https://commons.wikimedia.org/wiki/Emoji_One_colored_circles and originate from https://materialuicolors.co/ with level 600. Below a screenshot of the old and new colors:

![image](https://user-images.githubusercontent.com/1288217/185722545-98d02940-19d2-479f-83b9-ba11dc8aa1ef.png)

I hope it helps and/or inspires you. Keep up the good work. Kind regards, Maurits

**Comment by eddiejibson** [comment]
@mevdschee Really sorry I somehow just saw this. Just fixed this and is now merged, thanks again for all your suggestions, I plan on implementing them all.

Edward

**Comment by mevdschee** [comment]
Hi Edward, you are so kind. Thank you for your positive feedback and the great project. Keep it up! Kindest regards, Maurits
