### ISSUE TITLE
Bold parameter true/false

### ISSUE THREAD

**Issue by Mozzo1000** [eddiejibson/avatars#3]
Hi,

 I am wondering if this is intended behaviour or not when setting bold, according to your documentation it should be `bold=true` however I tested it and it seems that as long as `&bold` is in the url it will set the font to bold.

Example urls, all are bold even though I set bold to false or provide non-boolean argument.
https://avatar.oxro.io/avatar.svg?name=Eddie&background=ff6b6b&caps=3&bold=true
https://avatar.oxro.io/avatar.svg?name=Eddie&background=ff6b6b&caps=3&bold=false
https://avatar.oxro.io/avatar.svg?name=Eddie&background=ff6b6b&caps=3&bold
https://avatar.oxro.io/avatar.svg?name=Eddie&background=ff6b6b&caps=3&bold=whatever

**Comment by eddiejibson** [comment]
Should be fixed now, thanks for letting me know - was a silly little mistake :) Also apologies for the long response time.
