### ISSUE TITLE
Rounded pictures

### ISSUE THREAD

**Issue by HerrSammyDE** [eddiejibson/avatars#4]
Please build in that one gets the images also directly rounded.

Here is an example parameter "rounded=1"
- 1 stands for rounded
- 0 stands for not rounded

**Comment by eddiejibson** [comment]
@HerrSammyDE Interesting, never thought it'd really be used as you can just use the old `border-radius` in CSS. 

Although, always love some suggestions and will implement this tonight.

Sorry about the late reply, seems like I never get GH notifications anymore :sob:
