### ISSUE TITLE
Error when using supplied Generator file. 

### ISSUE THREAD

**Issue by lazysod** [eddiejibson/avatars#9]
When attempting to use the generator php file the following error is given: 

error on line 2 at column 1: Extra content at the end of the document
![Screenshot 2021-12-16 at 08 48 43](https://user-images.githubusercontent.com/1985101/146338520-aac35e23-578e-447e-8c8a-537364114ef4.png)

**Comment by eddiejibson** [comment]
@lazysod This should be resolved, it may be because you are missing the PHP extensions required. Please consider inspecting the page code in browser for further information.

Good luck.
